version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://your-gitlab-domain.com'
    networks:
      - gitlab_network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
    environment:
      - CI_SERVER_URL=http://your-gitlab-domain.com/
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_TLS_CERTDIR=""
      - RUNNER_EXECUTOR=docker
    networks:
      - gitlab_network

  docker:
    image: docker:latest
    container_name: docker
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_network

networks:
  gitlab_network:
    driver: bridge
