---
- name: Policy as Code
  gather_facts: true
  hosts: all
  vars_files:
    - vars/global_vars.yml
  tasks:
    - name: Setup GitLab w/Runners
      ansible.builtin.include_role:
        name: jonzeolla.labs.gitlab_runner

    - name: Setup the demo repos
      ansible.builtin.include_role:
        name: demo-repos
