---
name: "CI"

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install Task
        uses: arduino/setup-task@v2
      - name: Initialize the repo
        run: task -v init
      - name: Set up QEMU for cross-platform emulation
        uses: docker/setup-qemu-action@v3
      - name: Build
        run: task -v build
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Test
        run: task -v test -- debug
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Generate the SBOMs
        run: task -v sbom
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Set env var for unique artifact uploads
        run: echo SANITIZED_PLATFORM="$(echo "${{ matrix.platform }}" | sed 's/\//_/g')" >> $GITHUB_ENV
      - name: Upload the SBOMs to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: SBOM-${{ env.SANITIZED_PLATFORM }}
          path: sbom.*.json
          if-no-files-found: error
      - name: Generate vuln scan results
        run: task -v vulnscan
        env:
          PLATFORM: ${{ matrix.platform }}
      - name: Upload the vuln scan results to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Vulns-${{ env.SANITIZED_PLATFORM }}
          path: vulns.*.json
          if-no-files-found: error
